#if !canImport(ObjectiveC)
import XCTest

extension Sr25519Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Sr25519Tests = [
        ("testInit", testInit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Sr25519Tests.__allTests__Sr25519Tests),
    ]
}
#endif
