#if !canImport(ObjectiveC)
import XCTest

extension Sr25519DeriveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Sr25519DeriveTests = [
        ("testDeriveHardKnown", testDeriveHardKnown),
        ("testDeriveSoftKnown", testDeriveSoftKnown),
    ]
}

extension Sr25519KeyPairTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Sr25519KeyPairTests = [
        ("testKeyPairFromSeed", testKeyPairFromSeed),
        ("testSignAndVerifyInvalid", testSignAndVerifyInvalid),
        ("testSignAndVerifyValid", testSignAndVerifyValid),
        ("testVerifyExtisting", testVerifyExtisting),
    ]
}

extension Sr25519SeedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Sr25519SeedTests = [
        ("testFromData", testFromData),
        ("testRandom", testRandom),
    ]
}

extension Sr25519VrfTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Sr25519VrfTests = [
        ("testResultNotLess", testResultNotLess),
        ("testSignAndCheck", testSignAndCheck),
        ("testVerify", testVerify),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Sr25519DeriveTests.__allTests__Sr25519DeriveTests),
        testCase(Sr25519KeyPairTests.__allTests__Sr25519KeyPairTests),
        testCase(Sr25519SeedTests.__allTests__Sr25519SeedTests),
        testCase(Sr25519VrfTests.__allTests__Sr25519VrfTests),
    ]
}
#endif
