#if !canImport(ObjectiveC)
import XCTest

extension Ed25519KeyPairTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Ed25519KeyPairTests = [
        ("testRandomShouldWork", testRandomShouldWork),
        ("testSeedShouldWork", testSeedShouldWork),
        ("testSignShouldWork", testSignShouldWork),
        ("testSignShouldWorkRawData", testSignShouldWorkRawData),
    ]
}

extension Ed25519SeedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Ed25519SeedTests = [
        ("testFromData", testFromData),
        ("testRandom", testRandom),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Ed25519KeyPairTests.__allTests__Ed25519KeyPairTests),
        testCase(Ed25519SeedTests.__allTests__Ed25519SeedTests),
    ]
}
#endif
